spring:
  # thymeleaf 配置
  thymeleaf:
    # 关闭缓存
    cache: false

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flash_sales
    username: root
    password: 123456
    hikari:
      #连接池名
      pool-name: DateHikariCP
      # 最小空闲连接出
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000(10分钟)
      idle-timeout: 600000
      #最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认30000(30秒)
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # Redis 缓存配置
  redis:
    # Redis 数据库索引（默认为0）
    database: 0
    # Redis 服务器地址
    host: localhost
    # Redis 服务器连接端口
    port: 6379
    # Redis 服务器连接密码（默认为空）
    # password:
    #超时时间
    timeout: 10000ms
    # 连接池配置
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 1024
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5

  web:
    #静态资源处理
    resources:
      #启用默认静态资源处理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间，单位秒
          max-age: 3600
      chain:
        #资源链中启用缓存，默认启用
        cache: true
        #启用资源链，默认禁用
        enabled: true
        #启用压缩资源(gzip,brotli)解析,默认禁用
        compressed: true
        #启用H5应用缓存，默认禁用
        html-application-cache: true
        #静态资源位置
        static-locations: classpath:/static/

# Mybatis 配置
mybatis:
  configuration:
    # mybatis 的日志输出，可以在控制台看到 mybatis 的执行过程
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mybatis 的下划线转驼峰命名
    map-underscore-to-camel-case: true


## RocketMQ 配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: my-group
